object Versions {
    const val gradlePlugin = "7.1.0"
    const val kotlin = "1.6.10"
    const val core = "1.7.0"
    const val activityKtx = "1.4.0"
    const val appCompact = "1.4.1"
    const val material = "1.5.0"
    const val constraintLayout = "2.1.3"
    const val hilt = "2.38.1"
    const val hiltViewModel = "1.0.0-alpha03"
    const val multidex = "2.0.1"
    const val jUnit5 = "5.8.2"
    const val jUnitExt = "1.4.0"
    const val mockk = "1.10.0"
    const val rxJava = "3.0.0"
    const val rxAndroid = "3.0.0"
    const val moshi = "1.12.0"
    const val room = "2.4.1"
}