object Versions {
    const val gradlePlugin = "7.1.0"
    const val kotlin = "1.6.10"
    const val core = "1.7.0"
    const val activityKtx = "1.4.0"
    const val appCompact = "1.4.1"
    const val material = "1.5.0"
    const val constraintLayout = "2.1.3"
    const val jUnit = "4.13.2"
    const val testJUnit = "1.1.3"
    const val espresso = "3.4.0"
    const val hilt = "2.38.1"
    const val hiltViewModel = "1.0.0-alpha03"
    const val multidex = "2.0.1"
}